config/routes.rb
Pimp::Application.routes.draw do
  
  resources :pictures
  match "/pictures" => "pictures#create", via: :options
  
  resources :pics

  resources :events

  resources :items_dudes

  resources :dudes
  match "/dudes" => "dudes#create", via: :options
  resources :owners
  match "/owners" => "owners#create", via: :options
  match "/owners/:id" => "owners#destroy", via: :options
  resources :items
  match "/items" => "items#create", via: :options
  match "/items/:id" => "items#destroy", via: :options

  

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :items_dudes
  has_many :items, through: :items_dudes
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => [:create]
  respond_to :js
  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(:name => params[:name])
   respond_to do |format|
      if @owner.save
        format.html { render status: 200, nothing: true}
        format.json { render action: 'show', status: :created, location: @owner }
    end
   end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing owners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.name %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @owner.name %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>