config/routes.rb
Pimp::Application.routes.draw do
  
  resources :pictures
  match "/pictures" => "pictures#create", via: :options
  
  resources :pics

  resources :events

  resources :items_dudes

  resources :dudes
  match "/dudes" => "dudes#create", via: :options
  resources :owners
  match "/owners" => "owners#create", via: :options
  match "/owners/:id" => "owners#destroy", via: :options
  resources :items
  match "/items" => "items#create", via: :options
  match "/items/:id" => "items#destroy", via: :options

  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => [:create]
  respond_to :js
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    Picture.create(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Owner was successfully created.' }
        format.json { render action: 'show', status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:pic)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pic %><br>
    <%= f.text_field :pic %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <thead>
    <tr>
      <th>Pic</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.pic %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pic:</strong>
  <%= @picture.pic %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>