config/routes.rb
Pimp::Application.routes.draw do
  
  resources :pictures
  match "/pictures" => "pictures#create", via: :options
  
  resources :pics

  resources :events

  resources :items_dudes

  resources :dudes
  match "/dudes" => "dudes#create", via: :options
  resources :owners
  match "/owners" => "owners#create", via: :options
  match "/owners/:id" => "owners#destroy", via: :options
  resources :items
  match "/items" => "items#create", via: :options
  match "/items/:id" => "items#destroy", via: :options

  

end

app/models/items_dude.rb
class ItemsDude < ActiveRecord::Base
  belongs_to :item
  belongs_to :owner
end

app/controllers/items_dudes_controller.rb
class ItemsDudesController < ApplicationController
  before_action :set_items_dude, only: [:show, :edit, :update, :destroy]

  # GET /items_dudes
  # GET /items_dudes.json
  def index
    @items_dudes = ItemsDude.all
  end

  # GET /items_dudes/1
  # GET /items_dudes/1.json
  def show
  end

  # GET /items_dudes/new
  def new
    @items_dude = ItemsDude.new
  end

  # GET /items_dudes/1/edit
  def edit
  end

  # POST /items_dudes
  # POST /items_dudes.json
  def create
    @items_dude = ItemsDude.new(items_dude_params)

    respond_to do |format|
      if @items_dude.save
        format.html { redirect_to @items_dude, notice: 'Items dude was successfully created.' }
        format.json { render action: 'show', status: :created, location: @items_dude }
      else
        format.html { render action: 'new' }
        format.json { render json: @items_dude.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items_dudes/1
  # PATCH/PUT /items_dudes/1.json
  def update
    respond_to do |format|
      if @items_dude.update(items_dude_params)
        format.html { redirect_to @items_dude, notice: 'Items dude was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @items_dude.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items_dudes/1
  # DELETE /items_dudes/1.json
  def destroy
    @items_dude.destroy
    respond_to do |format|
      format.html { redirect_to items_dudes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_items_dude
      @items_dude = ItemsDude.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def items_dude_params
      params.require(:items_dude).permit(:id_items, :id_dudes)
    end
end

app/helpers/items_dudes_helper.rb
module ItemsDudesHelper
end

app/views/items_dudes/_form.html.erb
<%= form_for(@items_dude) do |f| %>
  <% if @items_dude.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@items_dude.errors.count, "error") %> prohibited this items_dude from being saved:</h2>

      <ul>
      <% @items_dude.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_items %><br>
    <%= f.number_field :id_items %>
  </div>
  <div class="field">
    <%= f.label :id_dudes %><br>
    <%= f.number_field :id_dudes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items_dudes/edit.html.erb
<h1>Editing items_dude</h1>

<%= render 'form' %>

<%= link_to 'Show', @items_dude %> |
<%= link_to 'Back', items_dudes_path %>

app/views/items_dudes/index.html.erb
<h1>Listing items_dudes</h1>

<table>
  <thead>
    <tr>
      <th>Id items</th>
      <th>Id dudes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items_dudes.each do |items_dude| %>
      <tr>
        <td><%= items_dude.id_items %></td>
        <td><%= items_dude.id_dudes %></td>
        <td><%= link_to 'Show', items_dude %></td>
        <td><%= link_to 'Edit', edit_items_dude_path(items_dude) %></td>
        <td><%= link_to 'Destroy', items_dude, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Items dude', new_items_dude_path %>

app/views/items_dudes/new.html.erb
<h1>New items_dude</h1>

<%= render 'form' %>

<%= link_to 'Back', items_dudes_path %>

app/views/items_dudes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id items:</strong>
  <%= @items_dude.id_items %>
</p>

<p>
  <strong>Id dudes:</strong>
  <%= @items_dude.id_dudes %>
</p>

<%= link_to 'Edit', edit_items_dude_path(@items_dude) %> |
<%= link_to 'Back', items_dudes_path %>